function res = msplitapply(fun,varargin)
G = varargin{end};
varargin = [ varargin(1:end-1) ...
             { reshape(1:numel(G),size(G,1),size(G,2)) } ...
             varargin(end) ];
[split_res,idx] = cmp_splitapply(@(varargin) deal({ fun(varargin{1:end-1}) }, ...
                                                  { varargin{end} }), ...
                                 varargin{:});
res = recombine(split_res,idx,G);
